CLI args test & fix
iterait/emloop pull request #50
Opened 2019-01-02 12:05 UTC by gdynusa

closes #39

2019-01-02 16:20 UTC, petrbel commented on emloop/utils/config.py
> +                stream_conf[key] = value
these three lines are actually same as the ones at L45 - couldn't we make it somehow simpler?

2019-01-04 08:02 UTC, petrbel submitted a review, later dismissed
almost there

2019-01-04 08:02 UTC, petrbel commented on emloop/utils/config.py
>          conf = config
is there any reason for this?

2019-01-04 08:02 UTC, petrbel commented on emloop/utils/config.py
> +            for stream in eval_conf:
instead of iterating the dict keys and then indexing into the dict using these keys, you can simply iterate through the dict values, e.g. `for stream_conf in eval_conf.values():` and get rid of the following line

2019-01-04 08:02 UTC, petrbel commented on emloop/utils/config.py
> +    def override_value(config_dict, dict_key, dict_key_prefix, arg_value):
a brif docstring (containing the information that the input parameter `config_dict` will be modified) would be helpful

2019-01-07 11:10 UTC, blazekadam requested changes

2019-01-07 11:10 UTC, blazekadam commented on emloop/utils/config.py
> +            for stream in eval_conf:
I do not get this!

We **do not want to always override all the `eval.*` options**. Moreover, it should be done **before** the cli options.

I.e.:
- load the config
- if specified, override the options from selected `eval.something` section
- override the options from cli args

2019-01-07 11:10 UTC, blazekadam commented on emloop/tests/cli/eval_test.py
> +    assert 'DummyModel created' in caplog.text
This is a quite indirect test. Just the function directly.

2019-01-07 11:20 UTC, blazekadam submitted a review, later dismissed
We need to:

- move lines https://github.com/iterait/emloop/blob/e56354cf85fdf4e67b4b9cf95fed978a86465c17/emloop/cli/eval.py#L39 to https://github.com/iterait/emloop/blob/e56354cf85fdf4e67b4b9cf95fed978a86465c17/emloop/cli/eval.py#L49 to the `load_config` function (the code should be in between the config load and cli args override)
- add `override_eval` argument to the `load_config` function 
- unit test it
- update docstring (ofc)

2019-01-08 13:34 UTC, petrbel reviewed
I like it. Is this what you thought of, @blazekadam ?

2019-01-08 13:34 UTC, petrbel commented on emloop/tests/utils/config_test.py
> +    """Test configuration is first overridden by eval section and CLI arguments then override everything."""
```suggestion
    """Test configuration is overridden by the eval section and subsequently by the CLI arguments."""
```

2019-01-08 13:34 UTC, petrbel commented on emloop/tests/utils/config_test.py
> +    # no cl_arguments nor override_stream specified - no override
```suggestion
    # neither cl_arguments nor override_stream specified - no override
```

2019-01-08 13:34 UTC, petrbel commented on emloop/utils/config.py
> +                config[subsection].update(deepcopy(update_section[subsection]))
please add a brief comment explaining why `deepcopy` is indeed required

2019-01-21 10:48 UTC, blazekadam requested changes

2019-01-21 10:48 UTC, blazekadam commented on emloop/cli/eval.py
> -    Configuration is updated by the respective predict.stream_name section, in particular:
This is still true.

2019-01-21 10:48 UTC, blazekadam commented on emloop/tests/utils/config_test.py
> +            train:
We do not usually eval train but its alright.

2019-01-21 10:48 UTC, blazekadam commented on emloop/tests/utils/config_test.py
> +    config_0 = {'model': {'class': 'Model', 'io': {'in': ['a'], 'out': ['b']}, 'outputs': ['c']},
You dont need to specify the whole dict (it is hard to find out what is actually tested). Just test the respective sections in the config.

2019-01-21 10:48 UTC, blazekadam commented on emloop/tests/utils/config_test.py
> +    cl_arguments = ['dataset.class=CliDataset', 'model.io.in=[m]']
`cli_arguments`

2019-01-21 10:48 UTC, blazekadam commented on emloop/utils/config.py
> +def load_config(config_file: str, additional_args: typing.Iterable[str]=(), override_stream: str=None) -> dict:
`Optional[str]`

2019-01-21 10:51 UTC, petrbel commented
@gdynusa could you pls adapt the comments pls?

2019-01-25 21:32 UTC, blazekadam approved these changes
Thank you @gdynusa the tests are way better now!

2019-01-28 09:19 UTC, merged