Add stopping condition to MainLoop
iterait/emloop pull request #81
Opened 2020-03-17 12:23 UTC by moraval

2020-03-17 12:57 UTC, blazekadam requested changes
Please implement some tests for this.

2020-03-17 12:57 UTC, blazekadam commented on emloop/main_loop.py
> +                 epochs_count: int=1,
```suggestion
                 epochs_count: Optional[int]=None,
```
lets make this `None` by default and do not stop if its not specified

2020-03-18 10:26 UTC, blazekadam commented
I still miss the tests...

2020-03-18 10:33 UTC, moraval commented
I didn't see the comment.. Will do.

2020-03-18 11:47 UTC, blazekadam approved these changes

2020-03-18 11:47 UTC, merged